package com.umlcollab.server.models;

import java.time.LocalDateTime;

/**
 * Represents a user in the system.
 * Fields match the `Users` table in MySQL.
 */
public class User {
    private int id;                  // corresponds to user_id in DB
    private String username;
    private String email;
    private String password;
    private LocalDateTime createdAt;

    // Constructor for new users (id will be auto-generated by DB)
    public User(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.createdAt = null;
    }

    // Constructor for fetching users from DB
    public User(int id, String username, String email, String password, LocalDateTime createdAt) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.password = password;
        this.createdAt = createdAt;
    }

    // Getters
    public int getId() { return id; }
    public String getUsername() { return username; }
    public String getEmail() { return email; }
    public String getPassword() { return password; }
    public LocalDateTime getCreatedAt() { return createdAt; }

    // Setter for password (for updates)
    public void setPassword(String password) { this.password = password; }
}
